### ISSUE TITLE
GPL is problematic

### ISSUE THREAD

**Issue by reem** [michaelsproul/rust_sequence_trie#16]
Somebody pointed out to me on IRC the other day that this is licensed GPL-3.0 but iron/mount uses it and is licensed MIT, which is incompatible. 

It's pretty much a non-starter for me to relicense iron/mount under the GPL, so unfortunately we'd have to cut this dependency and implement things some other way if we can't relicense this as something MIT compatible.

**Comment by michaelsproul** [comment]
Yeah, I just slapped a GPL license on it as it used to be my go-to license. Recently I've been licensing things under an MIT license, so I'll update this project accordingly. It may not be for a week or so though as I'm travelling without a computer.

**Comment by reem** [comment]
Ok, that sounds good. I just wanted to make sure this wasn't going to be a problem down the line.
