### ISSUE TITLE
how to use SequenceTrie for an "autocompletion" use case

### ISSUE THREAD

**Issue by allan-simon** [michaelsproul/rust_sequence_trie#19]
hello

i have the following use case

i enter a list of words into the trie
i then wants, given an arbitrary utf-8 string,   get back a vector (possibly empty) of all the words in my trie starting with that string 

I'm fairly new to rust and your crate, 

I've started to do something like this 

```
extern crate sequence_trie;

use sequence_trie::SequenceTrie;
fn main() {
     
    let mut trie = SequenceTrie::<u8, ()>::new();
    trie.insert("wo".to_string().as_ref(), ());
    trie.insert("wow".to_string().as_ref(), ());
    trie.insert("wowthis".to_string().as_ref(), ());
    trie.insert("prout".to_string().as_ref(), ());
    trie.insert("zout".to_string().as_ref(), ());
    trie.insert("tu".to_string().as_ref(), ());


    let values : Vec<&[u8]> = match trie.get_ancestor_node("wo".to_string().as_ref()) {
        Some(x) => x.keys().fold(
            Vec::new(),
            |mut v, k| {
                // some magic code to transform k which is a Vec<&u8>  into a  String 
                // but String::from_utf8(k)  does not work as it's Vec<&u8>  and not a Vec<u8>
                println!("{:?}", k);
                v   
            }   
        ),  
        None => Vec::new()
    };  
    println!("{:?}", values);
}
~                 

```
but it seems that actually get_ancestor_node  + keys does not do what i think it would 
(i.e retrieve the common node, and with .keys retrieve all the keys contained into that sub-tree) 

any help would be welcome

**Comment by allan-simon** [comment]
I've also seen that you have a radix tree implementation but it's actually lacking a lot of methods that suffix trie has (and specifically the one that i would need for my use case)

**Comment by michaelsproul** [comment]
Hi @allan-simon, thanks for your interest in this library!

I've gotten your example working, but it's not particularly efficient or elegant:

```rust
extern crate sequence_trie;

use std::str;
use sequence_trie::SequenceTrie;

fn main() {
    let mut trie = SequenceTrie::<u8, ()>::new();

    trie.insert("wo".as_ref(), ());
    trie.insert("wow".as_ref(), ());
    trie.insert("wowthis".as_ref(), ());
    trie.insert("prout".as_ref(), ());
    trie.insert("zout".as_ref(), ());
    trie.insert("tu".as_ref(), ());

    // Look up the node for the prefix (Option<&SequenceTrie>).
    let prefix = "wo";
    let node = trie.get_node(prefix.as_ref());

    // Iterate over the keys below the given node, converting
    // Vec<&u8> keys to Strings.
    let values: Vec<String> = node.map_or(vec![], |node| {
        node.keys().map(|v| {
            // All nodes below the prefix have the prefix excluded from
            // their key, so we have to add it back on...
            let mut string_key = String::with_capacity(prefix.len() + v.len());
            string_key.push_str(prefix);

            let byte_vec: Vec<u8> = v.into_iter().map(|b| *b).collect();
            string_key.push_str(str::from_utf8(&byte_vec).unwrap());

            string_key
        }).collect()
    });

    println!("{:?}", values);
}
```

There's a lot of mucking around (and a few allocations) to convert the `Vec<&u8>` into a `String`. The `unwrap` is particularly annoying, as we know the vectors in the trie correspond to valid UTF-8 strings. Another option would be to use insert each word with a `&str/String` version as its value, i.e. `SequenceTrie<u8, String>`. However this would require a `.values()` iterator, which doesn't exist (yet)!

The other bad thing about this, is that the above example misses the `"wow"` key due to an oversight in `.keys()`. I'll fix that up ASAP, and add some tests.

On my computer it prints this:

```
["wowthis"]
```

But should print:

```
["wow", "wowthis"]
```

One final thing to note is that `SequenceTrie` is slow for long keys due to its nesting of HashMaps. To get good performance in a case like yours I think the radix trie would be better, but I haven't gotten around to adding those extra methods, as you noticed. If you'd like to help add features to either library that would be amazing :smile:.

**Comment by allan-simon** [comment]
thanks a lot ,
yes I do agree i got the same impression that doing the conversion would not be elegant
fort long keys, fortunately I plan to use it to rewrite in rust this web services https://github.com/allan-simon/sinoparserd  so as it is for Chinese words, the string for 90% of them don't go over 3 chinese characters

I definitely can try to help, however I think I've a less academical background as your and i'm fairly new to rust, but i will give it a try.

On a side note as you've implemented several kind of Trie, did you look to HAT-trie ? https://en.wikipedia.org/wiki/HAT-trie

**Comment by allan-simon** [comment]
I've seen you commited, is it possible that you bump a new version ? :)

**Comment by michaelsproul** [comment]
@allan-simon: Done! :smile:

The example from before prints `["wo", "wow", "wowthis"]`, which I think is good.

Thanks for giving me the motivation to fix the iterators! Good luck with your application!

**Comment by allan-simon** [comment]
haha, you're very welcome, if i can motivate people to do stuff so that I don't have to implement it myself for sure i will do it :P

**Comment by michaelsproul** [comment]
The beauty of open source!

By the way, I haven't tried implementing a HAT-Trie - I read a bit about them but settled on the simpler radix trie design. It'd be interesting to see one in Rust, but I think two tries is enough for now haha.

**Comment by allan-simon** [comment]
sure, i was secretly hoping that you started a fixation on implementing all the type of trie in the world :( 

more seriously, i've adapted my code to your suggestions and now it looks like 


extern crate sequence_trie;



```
use sequence_trie::SequenceTrie;

fn main() {
    let mut trie = SequenceTrie::<u8, &str>::new();

    trie.insert("wo".as_ref(),"wo");
    trie.insert("wow".as_ref(), "wow");
    trie.insert("wowthis".as_ref(), "wowthis");
    trie.insert("prout".as_ref(), "prout");
    trie.insert("zout".as_ref(), "zout");
    trie.insert("tu".as_ref(), "tu");

    // Look up the node for the prefix (Option<&SequenceTrie>).
    let prefix = "wo";
    let node = trie.get_node(prefix.as_ref());

    let values: Vec<&str> = node.map_or(vec![], |node| {
        node.values().map(|v| *v ).collect()
    });

    println!("{:?}", values);
}
```

it looks indeed more straightforward to read now

**Comment by michaelsproul** [comment]
That's much nicer! Cool!

**Comment by allan-simon** [comment]
yes, now the ultimate things , would to be able to transform my  HashSet directly into a Trie 

```
fn get_words() -> HashSet<String>  {

    let mut s = String::new();
    let _  = File::open("data/words.json").unwrap().read_to_string(&mut s); 

    json::decode(&s).unwrap()
}
```

but I think i can handle it myself, if I get anything interesting that i can backport here, I will create a PR for you.
