### ISSUE TITLE
Try BTreeMap as backing storage

### ISSUE THREAD

**Issue by michaelsproul** [michaelsproul/rust_sequence_trie#30]
Might be nice to be able to switch between a HashMap and a BTreeMap using `#cfg[]` and a Cargo feature.

**Comment by lespea** [comment]
Are you planning on doing a release soon with this feature enabled?

**Comment by michaelsproul** [comment]
Good point! I'll try to get to this tomorrow!

**Comment by lespea** [comment]
Awesome, thanks!

**Comment by michaelsproul** [comment]
Done!
